# Generated by Django 6.1.1 on 2026-09-28 13:41

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('delivery_fee', models.DecimalField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('role', models.CharField(choices=[('WAITER', 'waiter'), ('COOK', 'cook'), ('DELIVERER', 'deliverer'), ('MANAGER', 'manager')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('payment_method', models.CharField(choices=[('CASH', 'cash'), ('PIX', 'pix'), ('DEBIT', 'debit'), ('CREDIT', 'credit'), ('VA_VR', 'va_vr')], max_length=50)),
                ('value', models.DecimalField()),
            ],
        ),
    ]
