# Generated by Django 6.1.1 on 2026-09-28 13:41

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('notes', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('multiplier', models.DecimalField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('KG', 'kg'), ('L', 'l'), ('UNIT', 'unit')], max_length=50)),
                ('provider', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('quantity', models.PositiveIntegerField()),
                ('total_value', models.DecimalField()),
                ('category', models.CharField(choices=[('DELVERY', 'delivery'), ('PHONE', 'phone'), ('LOCAL', 'local')], max_length=50)),
                ('status', models.CharField(choices=[('RECEIVED', 'received'), ('PREPARING', 'preparing'), ('READY', 'ready'), ('IN_TRANSIT', 'in_transit'), ('DELIVERED', 'delivered'), ('CANCELED', 'canceled')], max_length=50)),
                ('cover', models.PositiveIntegerField(null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('DRINK', 'drink'), ('UNITARY', 'unitary'), ('PORTION', 'portion')], max_length=50)),
                ('value', models.DecimalField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductsOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('SMALL', 'small'), ('MEDIUM', 'medium'), ('LARGE', 'large')], max_length=120)),
                ('is_combo', models.BooleanField(default=False)),
            ],
        ),
    ]
